### ISSUE TITLE
ImportError: No module named pca

### ISSUE THREAD

**Issue by sixin-zh** [dismalpy/dismalpy#2]
Hi,

Can you check if there's no longer module PCA in statsmodels? 
Can we remove the line 21 in the file dynamic_factor.py?

The way it is installed is as follows: 
$PY2 -m pip install Pandas SciPy NumPy Patsy Cython Matplotlib Nose
$PY2 -m pip install git+http://github.com/statsmodels/statsmodels.git
$PY2 -m pip install dismalpy==0.2.3
$PY2 -m pip install PySide

$PY2 is the python of version 2.7.12
Thanks.

p.s.

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/sixzhang/py2june/exe/python2/lib/python2.7/site-packages/dismalpy/**init**.py", line 13, in <module>
    from . import ssm
  File "/home/sixzhang/py2june/exe/python2/lib/python2.7/site-packages/dismalpy/ssm/**init**.py", line 57, in <module>
    from .dynamic_factor import DynamicFactor
  File "/home/sixzhang/py2june/exe/python2/lib/python2.7/site-packages/dismalpy/ssm/dynamic_factor.py", line 15, in <module>
    from .compat import mlemodel, dynamic_factor
  File "/home/sixzhang/py2june/exe/python2/lib/python2.7/site-packages/dismalpy/ssm/compat/dynamic_factor.py", line 21, in <module>
    from statsmodels.tools.pca import PCA
ImportError: No module named pca

**Comment by adam-rysanek** [comment]
Can confirm this issue. I encounter the same error upon following the same steps. I'm running Python 2.7.12 on OSX El Capitan.

**Comment by adam-rysanek** [comment]
Maybe found a simple fix. Seems like statsmodels relocated the 'pca' class with an update to v.8.0rc1 in June 2016: https://github.com/statsmodels/statsmodels/commit/5cdda079f904ba34459909078491f391587905d3#diff-cf722d379ceb3aa8d7acab9a0c67d408

From that update, 'pca' is no longer a class within statsmodels.tools, but within statsmodels.multivariate.

I thus make the simple change in dismalpy/ssm/compat/dynamic_factor.py:

**Original**
```python
from statsmodels.tools.pca import PCA
```

**Modified**
```python
from statsmodels.multivariate.pca import PCA
```

This at least rectifies the bug faced on import. I haven't tested any further application of dismalpy yet.

**Comment by zachmayer** [comment]
@adam-rysanek Could you make a PR to fix the issue?

**Comment by LaurentBerder** [comment]
I also encounter the same error on `import dismalpy`.
However, when I try to follow your recommendation, @adam-rysanek, there's no code mentioning `statsmodels.tools.pca` in any of the files (including dismalpy/ssm/compat/dynamic_factor.py).
So I can't rectify the problem.
